app = "eternal-garden-c575c815-d280-4008-b627-c7def7bad598"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = 'production'

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1